name: Cancel GitHub actions
description: Cancel GitHub actions when a ref is deleted or PR is closed

inputs:
  githubToken:
    required: true
    default: '${{github.token}}'
    description: GitHub access token
  ref:
    required: true
    default: '${{github.ref}}'
    description: The Git ref that was deleted or closed
  prNumber:
    required: false
    description: The Pull Request number if applicable
  dryRun:
    required: true
    default: 'false'
    description: Set to 'true' to enable dry run

runs:
  using: node20
  main: 'dist/index.js'
